apiVersion: v1
kind: Pod
metadata:
    name: app-pod
    labels:
      app: ticker
      tier: app
spec:
 containers:
   - name: server
     image: "slashdeploy/microservice-example:server-v1"
     ports:
       - containerPort: 6379
         protocol: TCP
     env:
       - name: REDIS_URL
         value: "redis://$(TICKER_DATA_TIER_SERVICE_HOST):(TICKER_DATA_TIER_SERVICE_PORT_REDIS)"
