apiVersion: v1
kind: Pod
metadata:
    name: app-pod
    labels:
      app: ticker
      tier: app
spec:
 containers:
   - name: server
     image: "slashdeploy/microservice-example:server-v1"
     ports:
       - containerPort: 8080
         protocol: TCP
     env:
       - name: REDIS_URL
         value: "redis://127.0.0.1:6379"
