apiVersion: v1
kind: Pod
metadata:
    name: example
    labels:
      app: example
      tier: app
spec:
 containers:
   - name: server
     image: "slashdeploy/microservice-example:server-v1"
     ports:
       - containerPort: 6379
         protocol: TCP
     env:
       - name: REDIS_URL
         value: "redis://$(EXAMPLE_DATA_TIER_SERVICE_HOST):(EXAMPLE_DATA_TIER_SERVICE_PORT_REDIS)"
