apiVersion: v1
kind: Pod
metadata:
    name: app-support-pod
    labels:
      app: ticker
      tier: support
spec:
 containers:
   - name: counter
     image: "slashdeploy/microservice-example:counter-v2"
     env:
       - name: API_URL
         value: "http://127.0.0.1:8080"

   - name: poller
     image: "slashdeploy/microservice-example:poller-v2"
     env:
       - name: API_URL
         value: "http://127.0.0.1:8080"
