apiVersion: v1
kind: Pod
metadata:
    name: ticker
    labels:
      name: ticker
spec:
 containers:
   - name: redis
     image: "redis:latest"
     imagePullPolicy: IfNotPresent
     ports:
       - containerPort: 6379
         protocol: TCP

   - name: server
     image: "slashdeploy/microservice-example:server-v1"
     ports:
       - containerPort: 8080
         protocol: TCP
     env:
       - name: "REDIS_URL"
         value: "redis://localhost:6379"

   - name: counter
     image: "slashdeploy/microservice-example:counter-v1"
     env:
       - name: "API_URL"
         value: "redis://localhost:8080"
